ALTER TABLE educational_programme
ADD name VARCHAR (100) NOT NULL DEFAULT "no name",
ADD ed_level INT UNSIGNED NOT NULL DEFAULT 0,
ADD faculty_id INT NOT NULL DEFAULT 1,
ADD CONSTRAINT FK_EdFac FOREIGN KEY (faculty_id) REFERENCES faculty(id) ON DELETE CASCADE ON UPDATE CASCADE;